# Generated by Django 3.1.7 on 2021-04-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='drivers',
            field=models.ManyToManyField(related_name='applications', to='drivers.Driver', verbose_name='Водители'),
        ),
        migrations.AddField(
            model_name='application',
            name='vehicles',
            field=models.ManyToManyField(related_name='applications', to='vehicles.Vehicle', verbose_name='Транспортные средства'),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_applications', to='companies.company', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer_additional_conditions',
            field=models.TextField(blank=True, verbose_name='Дополнительные условия с заказчиком'),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer_penalties',
            field=models.TextField(blank=True, verbose_name='Штрафные санкции с заказчиком'),
        ),
        migrations.AlterField(
            model_name='application',
            name='own_company_with_customer',
            field=models.ForeignKey(limit_choices_to={'is_own': True}, on_delete=django.db.models.deletion.PROTECT, related_name='own_company_with_customer_applications', to='companies.company', verbose_name='Своя компания с заказчиком'),
        ),
        migrations.AlterField(
            model_name='application',
            name='own_company_with_transporter',
            field=models.ForeignKey(limit_choices_to={'is_own': True}, on_delete=django.db.models.deletion.PROTECT, related_name='own_company_with_transporter_applications', to='companies.company', verbose_name='Своя компания с перевозчиком'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transporter',
            field=models.ForeignKey(limit_choices_to={'is_transporter': True}, on_delete=django.db.models.deletion.PROTECT, related_name='transporter_applications', to='companies.company', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transporter_additional_conditions',
            field=models.TextField(blank=True, verbose_name='Дополнительные условия с перевозчиком'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transporter_penalties',
            field=models.TextField(blank=True, verbose_name='Штрафные санкции с перевозчиком'),
        ),
    ]
