# Generated by Django 3.1.3 on 2020-11-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20201124_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('loading_date', models.DateField()),
                ('loading_address', models.CharField(max_length=250)),
                ('unloading_date', models.DateField()),
                ('unloading_address', models.CharField(max_length=250)),
                ('customer_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transporter_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='companies.company')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to='companies.company')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
