# Generated by Django 3.1.3 on 2020-11-24 11:28

from django.db import migrations
from mimesis import Generic, Datetime, Address
from mimesis.builtins import RussiaSpecProvider


def generate_requests(apps, schema_editor):
    mock = Generic("ru")
    mock.add_provider(RussiaSpecProvider)
    request = apps.get_model('requests_app', 'Request')
    company = apps.get_model('companies', 'Company')
    for _ in range(10):
        request.objects.create(
            number=f"{mock.numbers.integer_number(start=1)}/2020",
            loading_date=Datetime().date(start=2020, end=2020),
            loading_address=generate_address(),
            unloading_date=Datetime().date(start=2020, end=2020),
            unloading_address=generate_address(),
            customer=company.objects.filter(is_customer=True).order_by('?').first(),
            transporter=company.objects.filter(is_transporter=True).order_by('?').first(),
            customer_rate=mock.numbers.decimal_number(start=5000),
            transporter_rate=mock.numbers.decimal_number(start=5000)
        )


def generate_address():
    address = Address("ru")
    country = address.country()
    region = address.federal_subject()
    city = address.city()
    address = address.address()
    return f"{country}, {region}, {city}, {address}"


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
        ('companies', '0003_auto_20201124_1423'),
    ]

    operations = [
        migrations.RunPython(generate_requests)
    ]
