# Generated by Django 3.1.7 on 2021-04-18 18:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('slug', models.CharField(blank=True, max_length=50, verbose_name='Слаг')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'Мобильный'), ('desk', 'Стационарный')], default='mobile', max_length=50, verbose_name='Тип')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='Добавочный номер')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='drivers.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны водителей',
                'db_table': 'drivers_phones',
            },
        ),
        migrations.CreateModel(
            name='DriverPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('serial', models.CharField(max_length=10, verbose_name='Серийный номер')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='drivers.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Паспорт водителя',
                'verbose_name_plural': 'Паспорта водителей',
                'db_table': 'drivers_passports',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('serial', models.CharField(max_length=10, verbose_name='Серийный номер')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('start_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='drivers.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
                'db_table': 'drivers_licenses',
            },
        ),
    ]
