# Generated by Django 3.2.4 on 2021-06-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_short', models.CharField(max_length=255, verbose_name='Сокращенное наименование')),
                ('name_full', models.CharField(max_length=255, verbose_name='Полное наименование')),
            ],
            options={
                'db_table': 'company_types',
            },
        ),
    ]
