# Generated by Django 3.1.3 on 2020-11-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('types_of_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Заказчик')),
                ('is_transporter', models.BooleanField(default=False, verbose_name='Перевозчик')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('inn', models.PositiveSmallIntegerField(verbose_name='ИНН')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('type_of_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_of_companies.typeofcompany')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
