# Generated by Django 3.1.7 on 2021-04-03 13:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_short', models.CharField(max_length=255, unique=True, verbose_name='Сокращенное наименование')),
                ('name_full', models.CharField(max_length=255, unique=True, verbose_name='Полное наименование')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Может быть заказчиком')),
                ('is_transporter', models.BooleanField(default=False, verbose_name='Может быть перевозчиком')),
                ('is_own', models.BooleanField(default=False, verbose_name='Своя компания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_short', models.CharField(max_length=255, verbose_name='Сокращенное наименование')),
                ('name_full', models.CharField(max_length=255, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Организационно-правовая форма',
                'verbose_name_plural': 'Организационно-правовые формы',
                'db_table': 'company_types',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('post_address', models.CharField(blank=True, max_length=255, verbose_name='Почтовый адрес')),
                ('fact_address', models.CharField(blank=True, max_length=255, verbose_name='Фактический адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='companies.company', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
                'db_table': 'company_requisites',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.companytype', verbose_name='Правовая форма'),
        ),
    ]
