# Generated by Django 3.1.3 on 2020-11-24 11:23
from random import getrandbits

from django.db import migrations
from mimesis import Generic, Address
from mimesis.builtins import RussiaSpecProvider


def generate_companies(apps, schema_editor):
    mock = Generic("ru")
    mock.add_provider(RussiaSpecProvider)
    company = apps.get_model('companies', 'Company')
    type_if_company = apps.get_model('types_of_companies', 'TypeOfCompany')
    for _ in range(10):
        company.objects.create(
            is_customer=getrandbits(1),
            is_transporter=getrandbits(1),
            type_of_company=type_if_company.objects.order_by("?").first(),
            name=mock.business.company(),
            inn=mock.russia_provider.inn(),
            address=generate_address()
        )


def generate_address():
    address = Address("ru")
    country = address.country()
    region = address.federal_subject()
    city = address.city()
    address = address.address()
    return f"{country}, {region}, {city}, {address}"


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20201124_1405'),
        ('types_of_companies', '0002_auto_20201124_1418'),
    ]

    operations = [
        migrations.RunPython(generate_companies)
    ]
