# Generated by Django 3.1.7 on 2021-04-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('auto', 'Авто'), ('trailer', 'Прицеп')], max_length=50, verbose_name='Тип ТС')),
                ('mark', models.CharField(blank=True, max_length=255, verbose_name='Марка')),
                ('registration_number', models.CharField(max_length=25, verbose_name='Регистрационный номер')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(blank=True, max_length=50, verbose_name='Кузов')),
                ('carrying', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Грузоподъемность')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота')),
                ('top', models.BooleanField(default=False, verbose_name='Верхняя загрузка/выгрузка')),
                ('side', models.BooleanField(default=False, verbose_name='Боковая загрузка/выгрузка')),
                ('back', models.BooleanField(default=True, verbose_name='Задняя загрузка/выгрузка')),
                ('tail_lift', models.BooleanField(default=False, verbose_name='Гидроборт')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_parameters', to='vehicles.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Параметры транспортного средства',
                'verbose_name_plural': 'Параметры транспортных средств',
                'db_table': 'vehicle_parameters',
            },
        ),
    ]
