# Generated by Django 3.1.7 on 2021-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Слаг'),
        ),
    ]
