# Generated by Django 3.1.3 on 2020-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=20)),
                ('name_full', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'catalogs__types_of_companies',
            },
        ),
    ]
